config/routes.rb
SpringConference2012::Application.routes.draw do
  

  get "pages/home"
  get "pages/program"
  get "pages/schedule"
  get "pages/sponsors"
  get "pages/contact_us"
  get "pages/keynote"
  get "pages/registration"
  get "pages/educationals"
  get "pages/speaker_bios"
  get "pages/faq"
  get "pages/prizes"
  get "pages/terms_conditions"
  get "pages/venue"
  get "pages/about_calgary"
  get "pages/our_sponsors"
  get "pages/volunteers"
  get "pages/application"
  get "pages/about"
  get "pages/welcome_message"
  get "pages/about_tm"
  get "pages/planning_team"
  get "pages/disclaimer"
  

  root :to => "pages#home"
  match '/', :to => 'pages#home'
  match '/contact_us', :to => 'pages#contact_us'
  match '/schedule', :to => 'pages#schedule'
  match '/program', :to => 'pages#program'
  match '/sponsors', :to => 'pages#sponsors'
  match '/keynote', :to => 'pages#keynote'
  match '/registration', :to => 'pages#registration'
  match '/educationals', :to => 'pages#educationals'
  match '/speaker_bios', :to => 'pages#speaker_bios'
  match '/faq', :to => 'pages#faq'
  match '/prizes', :to => 'pages#prizes'
  match '/terms_conditions', :to => 'pages#terms_conditions'
  match '/venue', :to => 'pages#venue'
  match '/about_calgary', :to => 'pages#about_calgary'
  match '/our_sponsors', :to => 'pages#our_sponsors'
  match '/volunteers', :to => 'pages#volunteers'
  match '/application', :to => 'pages#application'
  match '/about', :to => 'pages#about'
  match '/welcome_message', :to => 'pages#welcome_message'
  match '/about_tm', :to => 'pages#about_tm'
  match '/planning_team', :to => 'pages#planning_team'
  match '/disclaimer', :to => 'pages#disclaimer'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :integer         not null, primary key
#  first_name              :string(255)
#  last_name               :string(255)
#  address                 :string(255)
#  city                    :string(255)
#  province                :string(255)
#  postal_code             :string(255)
#  home_phone              :string(255)
#  work_phone              :string(255)
#  fax                     :string(255)
#  email                   :string(255)
#  special_dietary_needs   :string(255)
#  home_club_name          :string(255)
#  home_club_number        :integer
#  toastmaster             :boolean
#  area                    :string(255)
#  club_executive_position :string(255)
#  tm_designation          :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#

class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :first_name, :last_name, :address, :city, 
                  :posta_code, :province, :home_phone, :work_phone,
                  :fax, :email, :special_dietary_needs, :home_club_name,
                  :home_club_number, :toastmaster, :area,
                  :club_executive_position, :tm_designation, :password,
		  :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name,	:presence => true,
 				:length	  => { :maximum => 30 }
  validates :last_name,		:presence => true,
 				:length	  => { :maximum => 30 } 
  validates :address,		:presence => true,
 				:length	  => { :maximum => 100 }
  validates :city,		:presence => true,
 				:length	  => { :maximum => 30 }
  validates :province,		:presence => true,
 				:length	  => { :maximum => 30 }
  validates :postal_code,	:presence => true,
 				:length	  => { :maximum => 7 }
  validates :home_phone,	:presence => true,
 				:length	  => { :maximum => 15 }
  validates :email,		:presence => true
				:format	  => { :with => email_regex }
				:uniqueness => { :case_sensitive => false }

  validates :password,		:presence     => true,
				:confirmation => true,
				:length       => { :within => 6..40 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def agenda
  end

  def feature_speakers_and_events
  end

  def sponsors
  end

  def contact_us
  end

  def photo_gallery
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Registration"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D42 Spring Convention || Take The Lead</title>
	<%= csrf_meta_tag %>
	<!--[if gte IE 9]>
	  <style type="text/css">
    		.gradient {
       			filter: none;
    		}
  	  </style>
	<![endif]-->
	<!--[if lt IE9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<~[endif]-->
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body class="twoColFixRtHdr">

<div id="container">
  <div id="header">

   <%= link_to image_tag("Banner_Medium_w980.png", :alt => "D42 Spring Convention || Take The Lead"), root_path %>
   
    
<!-- Drop-down menu -->
    
	<div id="nav">
		<ul>
			<li class="first"><%= link_to "Program", program_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Schedule", schedule_path , :class => "nav_links" %></li>
					<li><%= link_to "Keynote", keynote_path, :class => "nav_links" %></li>
					<li><%= link_to "Educationals", educationals_path, :class => "nav_links" %></li>
					<li><%= link_to "Speaker Bios", speaker_bios_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Registration", registration_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "FAQ", faq_path, :class => "nav_links" %></li>
					<li><%= link_to "Prizes", prizes_path, :class => "nav_links" %></li>
					<li><%= link_to "Terms & Conditions", terms_conditions_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Venue", venue_path, :class => "nav_links" %>
				<ul>					
					<li><%= link_to "About Calgary", about_calgary_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Sponsors", sponsors_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Our Sponsors", our_sponsors_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Volunteers", volunteers_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Application", application_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "About", about_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Welcome Messages", welcome_message_path, :class => "nav_links" %></li>
					<li><%= link_to "About TM", about_tm_path, :class => "nav_links" %></li>
					<li><%= link_to "Planning Team", planning_team_path, :class => "nav_links" %></li>
					<li><%= link_to "Contact Us", contact_us_path, :class => "nav_links" %></li>
				</ul>
			</li>
		</ul>
	</div>
  <!-- end #header --></div>
  <div id="sidebar1">
    <%= link_to "Register", registration_path, :class => "registration_button round" %>
    <br>
   <script src="http://widgets.twimg.com/j/2/widget.js"></script>
    <script>
       new TWTR.Widget({
         version: 2,
         type: 'profile',
         rpp: 4,
         interval: 30000,
         width: 200,
         height: 250,
         theme: {
           shell: {
             background: '#004265',
             color: '#ffffff'
           },
           tweets: {
             background: '#f2df74',
             color: '#000000',
             links: '#fc3200'
           }
         },
         features: {
            scrollbar: true,
            loop: false,
            live: true,
            behavior: 'all'
         }
      }).render().setUser('twitter').start();
      </script>



  <!-- end #sidebar1 --></div>

<%= yield %>

<!-- This clearing element should immediately follow the #mainContent div in order to force the #container div to contain all child floats --><br class="clearfloat" />
  <div id="footer">
	<div id="top_footer"><br><br></div>
	<div id="mid_footer" class="round"><br><p>sponsors logos</p><br></div>
   
	<div id="bottom_footer">
		<%= link_to "Home", root_path, :class => "footer_left" %><p class="footer_left"> | </p>
		<%= link_to "Disclaimer", disclaimer_path, :class => "footer_left" %><p class="footer_left"> | </p>
		<%= link_to "Contact Us", contact_us_path, :class => "footer_left" %>
		<p class="footer_right">Design by Matthew Dumont</p>
	</div>    

    <br />
  <!-- end #footer --></div>
<%= debug(params) if Rails.env.development? %>
<!-- end #container --></div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/about_calgary.html.erb
<h1>Pages#about_calgary</h1>
<p>Find me in app/views/pages/about_calgary.html.erb</p>

app/views/pages/about_tm.html.erb
<h1>Pages#about_tm</h1>
<p>Find me in app/views/pages/about_tm.html.erb</p>

app/views/pages/application.html.erb
<h1>Pages#application</h1>
<p>Find me in app/views/pages/application.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/feature_speakers_and_events.html.erb
<h1>Pages#feature_speakers_and_events</h1>
<p>Find me in app/views/pages/feature_speakers_and_events.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/keynote.html.erb
<h1>Pages#keynote</h1>
<p>Find me in app/views/pages/keynote.html.erb</p>

app/views/pages/photo_gallery.html.erb
<h1>Pages#photo_gallery</h1>
<p>Find me in app/views/pages/photo_gallery.html.erb</p>

app/views/pages/prizes.html.erb
<h1>Pages#prizes</h1>
<p>Find me in app/views/pages/prizes.html.erb</p>

app/views/pages/program.html.erb
<h1>Pages#program</h1>
<p>Find me in app/views/pages/program.html.erb</p>

app/views/pages/registration.html.erb
<h1>Pages#registration</h1>
<p>Find me in app/views/pages/registration.html.erb</p>

app/views/pages/terms_conditions.html.erb
<h1>Pages#terms_conditions</h1>
<p>Find me in app/views/pages/terms_conditions.html.erb</p>

app/views/pages/volunteers.html.erb
<h1>Pages#volunteers</h1>
<p>Find me in app/views/pages/volunteers.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>